# FROM maven:3.6.0-jdk-11-slim
FROM openjdk:8-jdk-alpine
RUN echo "Asia/Novosibirsk" > /etc/timezone
#
# ENV JAVA_HOME /opt/java8
RUN apk add --no-cache curl tar bash
ARG MAVEN_VERSION=3.3.9
ARG USER_HOME_DIR="/root"
RUN mkdir -p /usr/share/maven && \
curl -fsSL http://apache.osuosl.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar -xzC /usr/share/maven --strip-components=1 && \
ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"
# speed up Maven JVM a bit
ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
ENTRYPOINT ["/usr/bin/mvn"]

WORKDIR /opt/app

COPY pom.xml /opt/app
COPY MedicineSchedulerMaven.iml /opt/app
COPY src /opt/app/src

# RUN mvn -T 1C install && rm -rf target
RUN mvn clean compile assembly:single

# CMD ["java", "-jar", "target/MedicineSchedulerMaven-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.wcreators.Main"]
ENTRYPOINT ["java","-jar","target/MedicineSchedulerMaven-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.wcreators.Main"]
