alter table Agent drop foreign key FKjuquwk21jt39yntvgnvfqnnwv;
alter table agent_id drop foreign key FK36okx5mmyfsvs2uardevts97;
alter table agent_id drop foreign key FK2iln7jawkkhgq8xycs3v17eap;
alter table User_Medicine drop foreign key FKro2vil1y7822c1uifvoj97yxe;
alter table User_Medicine drop foreign key FK3oy0mbgsa20lgmivtcrwexbuw;
drop table if exists Agent;
drop table if exists agent_id;
drop table if exists Medicine;
drop table if exists User;
drop table if exists User_Medicine;
create table Agent (id binary(255) not null, agentId varchar(100) not null, agentType integer not null, user_id binary(255), primary key (id)) engine=InnoDB;
create table agent_id (UserEntity_id binary(255) not null, agents_id binary(255) not null, primary key (UserEntity_id, agents_id)) engine=InnoDB;
create table Medicine (id binary(255) not null, title varchar(256) not null, primary key (id)) engine=InnoDB;
create table User (id binary(255) not null, email varchar(256) not null, firstName varchar(100) not null, lastName varchar(100) not null, password varchar(100), primary key (id)) engine=InnoDB;
create table User_Medicine (user_id binary(255) not null, medicine_id binary(255) not null, primary key (user_id, medicine_id)) engine=InnoDB;
alter table agent_id add constraint UK_bodn36s1q3h7bknif5ich5bg unique (agents_id);
alter table Medicine add constraint UK_da33danj1tr1k3y3nlwahcnxi unique (title);
alter table User add constraint UK_e6gkqunxajvyxl5uctpl2vl2p unique (email);
alter table Agent add constraint FKjuquwk21jt39yntvgnvfqnnwv foreign key (user_id) references User (id);
alter table agent_id add constraint FK36okx5mmyfsvs2uardevts97 foreign key (agents_id) references Agent (id);
alter table agent_id add constraint FK2iln7jawkkhgq8xycs3v17eap foreign key (UserEntity_id) references User (id);
alter table User_Medicine add constraint FKro2vil1y7822c1uifvoj97yxe foreign key (medicine_id) references Medicine (id);
alter table User_Medicine add constraint FK3oy0mbgsa20lgmivtcrwexbuw foreign key (user_id) references User (id);
alter table Agent drop foreign key FKjuquwk21jt39yntvgnvfqnnwv;
alter table agent_id drop foreign key FK36okx5mmyfsvs2uardevts97;
alter table agent_id drop foreign key FK2iln7jawkkhgq8xycs3v17eap;
alter table User_Medicine drop foreign key FKro2vil1y7822c1uifvoj97yxe;
alter table User_Medicine drop foreign key FK3oy0mbgsa20lgmivtcrwexbuw;
drop table if exists Agent;
drop table if exists agent_id;
drop table if exists Medicine;
drop table if exists User;
drop table if exists User_Medicine;
create table Agent (id binary(255) not null, agentId varchar(100) not null, agentType integer not null, user_id binary(255), primary key (id)) engine=InnoDB;
create table agent_id (UserEntity_id binary(255) not null, agents_id binary(255) not null, primary key (UserEntity_id, agents_id)) engine=InnoDB;
create table Medicine (id binary(255) not null, title varchar(256) not null, primary key (id)) engine=InnoDB;
create table User (id binary(255) not null, email varchar(256) not null, firstName varchar(100) not null, lastName varchar(100) not null, password varchar(100), primary key (id)) engine=InnoDB;
create table User_Medicine (user_id binary(255) not null, medicine_id binary(255) not null, primary key (user_id, medicine_id)) engine=InnoDB;
alter table agent_id add constraint UK_bodn36s1q3h7bknif5ich5bg unique (agents_id);
alter table Medicine add constraint UK_da33danj1tr1k3y3nlwahcnxi unique (title);
alter table User add constraint UK_e6gkqunxajvyxl5uctpl2vl2p unique (email);
alter table Agent add constraint FKjuquwk21jt39yntvgnvfqnnwv foreign key (user_id) references User (id);
alter table agent_id add constraint FK36okx5mmyfsvs2uardevts97 foreign key (agents_id) references Agent (id);
alter table agent_id add constraint FK2iln7jawkkhgq8xycs3v17eap foreign key (UserEntity_id) references User (id);
alter table User_Medicine add constraint FKro2vil1y7822c1uifvoj97yxe foreign key (medicine_id) references Medicine (id);
alter table User_Medicine add constraint FK3oy0mbgsa20lgmivtcrwexbuw foreign key (user_id) references User (id);
